/*

                Name:  Fleming Siow Yi
       Serial Number:  4
               Class:  DAAA/FT/1B/03
    Admission Number:  p2011828
    
*/
'use strict';


exports.emailTemplate = async (user, info) => {

    var today = new Date();
    var dd = String(today.getDate()).padStart(2, '0');
    var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
    var yyyy = today.getFullYear();

    today = mm + '/' + dd + '/' + yyyy;

    let htmlMsg = `
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse; border: 1px solid #cccccc;">
            <tr>
                <td align="center" bgcolor="#70bbd9" style="padding: 40px 0 30px 0; background: #fc5b62;">
                    <img src="https://i.ibb.co/nwCY953/logo.png" alt="SPGames" width="300" height="110" style="display: block;" />
                </td>
            </tr>
            <tr>
                <td bgcolor="#ffffff" style="padding: 40px 30px 40px 30px;">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">

                        <tr>
                            <td style="color: #153643; font-family: Arial, sans-serif;">
                                <h1 style="font-size: 24px; margin: 0;">Your Purchase Was Successful!</h1>
                            </td>
                        </tr>

                        <tr>
                            <td style="color: #153643; font-family: Arial, sans-serif; font-size: 16px; line-height: 24px; padding: 20px 0 30px 0;">
                                <p style="margin: 0;">
                                    Hello ${user}! This is an autogenerated email confirming your purchase on ${today}. The total 
                                    purchasing cost of the games you bought were $${info.transaction.subtotal}. Addtionally, you 
                                    were given a $${info.transaction.gst_paid} GST and $${info.transaction.discount_given} discount. 
                                    Thus, your total amount payable adds up to 
                                    <span style="color: #fc5b62;">$${info.transaction.total_amt_payable}</span>. 
                                </p>
                            </td>
                        </tr>
                
                        <tr>
                            <td>
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">`;
    let i = 0;
    for (var p of info.purchases) {

        if (i % 2 === 0) {
            htmlMsg += `<tr>`
        };

        htmlMsg += `
        <td width="260" valign="top">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
                <tr>
                    <td>
                        <img src="${info.url}/image/${p.gamepic}" alt="" width="100%" height="140" style="display: block;" />
                    </td>
                </tr>
                <tr>
                    <td style="color: #153643; font-family: Arial, sans-serif; font-size: 16px; line-height: 24px; padding: 25px 0 0 0;">
                        <p style="margin: 0; margin-bottom: 5px;">
                            <strong style="text-decoration: underline;">Game Title</strong>
                            <p style="font-size: 12px;">${p.title}</p>
                        </p>
                        <p style="margin: 0; margin-bottom: 5px;">
                            <strong style="text-decoration: underline;">Price</strong>
                            <p style="font-size: 12px;">$${p.price}</p>
                        </p>
                        <p style="margin: 0;">
                            <strong style="text-decoration: underline;">Discount</strong>
                            <p style="font-size: 12px;">$${p.discount}</p>
                        </p>
                    </td>
                </tr>
            </table>
        </td>
        <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
        `;

        i++;

        if (i % 2 === 0 || i === info.purchases.length) {
            htmlMsg += `</tr>`
        };

    };
                                        
    htmlMsg +=  `
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td bgcolor="#ee4c50" style="padding: 30px 30px;">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
                        <tr>
                            <td style="color: #ffffff; font-family: Arial, sans-serif; font-size: 14px;">
                                <p style="margin: 0;">&reg; Fleming, SPGames 2021<br />
                                    <a href="http://ec2-13-212-197-22.ap-southeast-1.compute.amazonaws.com:8000" style="color: #ffffff;">Visit</a> SPGames</p>
                            </td>
                            <td align="right">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                    <tr>
                                        <td>
                                            <a href="http://www.twitter.com/">
                                                <img src="https://assets.codepen.io/210284/tw.gif" alt="Twitter." width="38" height="38" style="display: block;" border="0" />
                                            </a>
                                        </td>
                                        <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
                                        <td>
                                            <a href="http://www.twitter.com/">
                                                <img src="https://assets.codepen.io/210284/fb.gif" alt="Facebook." width="38" height="38" style="display: block;" border="0" />
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    `;

    return htmlMsg;
};


exports.usrRegistrationCfm = async (user, link) => {

    let htmlMsg = `
        <p style="font-weight: 100;">Dear <strong>${user}</strong>,</p>
        <p style="font-weight: 100;">Thank you for your interest in SPGames.</p>
        <p style="font-weight: 100;">Clicking the following link will verify your account on SPGames and 
        grant you access to post reviews and purchase our game listings.</p>
        <p style="font-weight: 100;">Confirmation Link: <strong>${link}</strong></p>
        <p style="font-weight: 100;">Please note that this link is uniquely assigned to you and is not to be shared with anyone else. 
        You are to observe the terms and conditions stipulated by SPGames, and API Terms of Service, as acknowledged in your 
        application, and refrain from hyperlinking your products and services directly to SPGames.</p>
        <p style="font-weight: 100;">Should you have any further queries, you may contact us at spgames@gmail.com.</p>
        <br/>
        <br/>
        <p style="font-weight: 100;">Cheers,</p>
        <p style="font-weight: 100;">SPGames</p>
        <p style="font-weight: 100; font-size: 11px;">
        *** If you are not the intended recipient of this email, please notify us right away at spgames@gmail.com and delete 
        this email from your system. ***</p>
    `;

    return htmlMsg;
};