/*

                Name:  Fleming Siow Yi
       Serial Number:  4
               Class:  DAAA/FT/1B/03
    Admission Number:  p2011828
    
*/
'use strict';


const nodemailer = require('nodemailer');
const mailGun = require('nodemailer-mailgun-transport');
const { api, domain } = require('../../config/env.config');


exports.nodeMailer = async (userEmail, subject='SPGames', text='This is an autogenerated message') => {

    const auth = {
        auth: {
            api_key: api,
            domain: domain
        }
    };
    const transporter = nodemailer.createTransport(mailGun(auth));

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: '"SPGames" <spgames@gmail.com>', 
        to: userEmail, 
        subject: subject, 
        text: text, 
        html: `<b>${text}</b>`, 
    });

    console.log('Message sent: %s', info.messageId);
};